### PR TITLE
Examining failed test output

### PR DESCRIPTION
**Pull request by tvlooy**
Add the first bits of this chapter. @SammyK what do you think is missing here?

I also added some debugging with valgrind and gdb examples.

### CODE REVIEW

**Comment by tvlooy** [comment]
Maybe an even better "obvious bad code example" is this:

```c
int isNegative(float arg)
{
    char *p = (char*) malloc(20);
    sprintf(p, "%f", arg);
    return p[0] == '-';
}
```

**Comment by jpauli** [comment]
We already got some debugging lines.

Please, see memory_debugging.rst  , this chapter explains valgrind and it is planned to explain gdb as well.
Perhaps you should merge your ideas against this file instead ?

**Comment by tvlooy** [comment]
@jpauli right! I totally overlooked that.
I removed that last commit and will take a look at the existing chapter first.

**Comment by SammyK** [comment]
Looks great - thanks @tvlooy! :) I'd also go into some detail about showing output from the console using `--show-*` flags for both run-tests directly and through make. And also an example showing the purpose of the `.sh` bash script.

**Comment by tvlooy** [comment]
@SammyK actually, I'm not sure how the ```.sh``` script should be used. Anything you can think of?

**Comment by tvlooy** [comment]
Hi peeps. Can this be merged?

**Comment by tvlooy** [comment]
@jpauli when does this appear on www.phpinternalsbook.com? It's still not there

**Comment by nikic** [comment]
@tvlooy It doesn't update automatically, someone will have to do a rebuild.

**Comment by nikic** [comment]
@tvlooy Rebuild done.

**Comment by tvlooy** [comment]
@nikic thanks buddy!

**Pull request merged**
