### PR TITLE
Install Sphinx before building release (GHA)

### PR DESCRIPTION
**Pull request by flavioheleno**
This PR fixes the build/publish automation introduced by #109.

Action Steps:

1. Installs Python 3.x;
2. Installs Sphinx;
3. Installs PHP 8.1;
4. Executes the release script.

### CODE REVIEW

**Comment by nikic** [comment]
Now the push is failing: https://github.com/phpinternalsbook/PHP-Internals-Book/runs/4781440717?check_suite_focus=true#step:7:53

**Comment by flavioheleno** [comment]
The action is probably doing something weird. I'll find a replacement that simply does a commit/push to the right branch. Sorry again for wasting your time!

**Comment by nikic** [comment]
Maybe use this one? https://github.com/marketplace/actions/deploy-to-github-pages It seems a lot more popular.

**Comment by flavioheleno** [comment]
I have no idea why I did not find that one when I was searching for an action. A new PR is open that replaces the current action with that one and I created a repo and tested it as well as with [act](https://github.com/nektos/act).

**Pull request merged**
