### PR TITLE
Moving files to php5 folder keeping the old links

### LINKED ISSUE #9: Update to PHP 7
Right now the book documents PHP 5. Presumably, we'll want to update it to PHP 7. How should we go about this?

I don't think that we should do this update in-place. Instead we should create separate PHP 5 and PHP 7 sections and add content to the PHP 7 section as it is updated.

### PR DESCRIPTION
**Pull request by thiagooak**
Fixes #9 

Creates a `php5` folder while keeping the old links working using `includes`

If this approach makes sense I'll do it to the other files.

Was thinking of moving `php7` up on the TOC also, but likely for another PR

### CODE REVIEW

**Comment by thiagooak** [comment]
@nikic would it make sense to take this approach? or are y'all considering dropping the PHP5 content?

**Comment by thiagooak** [comment]
I did some research on the redirect and it is doable with JS. There doesn't seem to be something baked into sphinx to do it. https://tech.signavio.com/2017/managing-sphinx-redirects

How painful would it be to just break those links? Is it fair to say that most people are now interested in PHP7? Would a 404 explaining the move be enough?

**Comment by thiagooak** [comment]
Since I'm illiterate in python I wrote something in PHP to handle the redirects, it generates static files. Not exactly elegant, but I think it makes sense to have this as part of the "build" process and not part of the actual book.

**Comment by nikic** [comment]
Looks like a reasonable approach to me. Someone will have to push a new build with this (unfortunately not automated...)

**Comment by nikic** [comment]
Better late than never ... merged and pushed a new build. Redirects working great. Thanks for doing this!

**Pull request closed without merging**
